/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ul_util_NativeBuffer */

#ifndef _Included_org_ul_util_NativeBuffer
#define _Included_org_ul_util_NativeBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    clear
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_clear
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    allocByteBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_ul_util_NativeBuffer_allocByteBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    freeByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_freeByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: ([FLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy___3FLjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: ([BILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy___3BILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jint, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: ([CILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy___3CILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jcharArray, jint, jobject, jint, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: ([SILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy___3SILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jshortArray, jint, jobject, jint, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: ([IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy___3IILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jintArray, jint, jobject, jint, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: ([JILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy___3JILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jlongArray, jint, jobject, jint, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: ([FILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy___3FILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jfloatArray, jint, jobject, jint, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: ([DILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy___3DILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jdoubleArray, jint, jobject, jint, jint);

/*
 * Class:     org_ul_util_NativeBuffer
 * Method:    copy
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_ul_util_NativeBuffer_copy__Ljava_nio_ByteBuffer_2ILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
